export const BREAKPOINTS = [970, 1580]
export const START_DATE = '2/24/20'
export const STATES = [
  'washington',
  'new-york',
  'california',
  'massachusetts',
  'georgia',
  'colorado',
  'florida',
  'new-jersey',
  'oregon',
  'texas',
  'illinois',
  'pennsylvania',
  'iowa',
  'maryland',
  'north-carolina',
  'south-carolina',
  'tennessee',
  'virginia',
  'arizona',
  'indiana',
  'kentucky',
  'nevada',
  'new-hampshire',
  'minnesota',
  'nebraska',
  'ohio',
  'rhode-island',
  'wisconsin',
  'connecticut',
  'hawaii',
  'oklahoma',
  'utah',
  'kansas',
  'louisiana',
  'missouri',
  'vermont',
  'alaska',
  'arkansas',
  'delaware',
  'idaho',
  'maine',
  'michigan',
  'mississippi',
  'montana',
  'new-mexico',
  'north-dakota',
  'south-dakota',
  'west-virginia',
  'wyoming',
  'alabama',
  // 'district-of-columbia',
  // 'diamond-princess',
  // 'grand-princess',
  // 'puerto-rico',
  // 'guam',
  // 'virgin-islands',
]
export const DEFAULT_SEO = {
  title: 'COVID-19',
  description: 'Covid-19 statistics for United States.',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://covidstats.app/',
    site_name: 'COVID-19 Stats',
    images: [
      {
        url: 'https://covidstats.app/images/og-image.png',
        alt: 'COVID-19',
      },
    ],
  },
  twitter: {
    handle: '@trillcyborg',
    site: '@trillcyborg',
    cardType: 'summary_large_image',
  }
}