export const BREAKPOINTS = [970, 1380]
export const START_DATE = '2/24/20'
export const STATES = [
  'washington',
  'new-york',
  'california',
  'massachusetts',
  'georgia',
  'colorado',
  'florida',
  'new-jersey',
  'oregon',
  'texas',
  'illinois',
  'pennsylvania',
  'iowa',
  'maryland',
  'north-carolina',
  'south-carolina',
  'tennessee',
  'virginia',
  'arizona',
  'indiana',
  'kentucky',
  'nevada',
  'new-hampshire',
  'minnesota',
  'nebraska',
  'ohio',
  'rhode-island',
  'wisconsin',
  'connecticut',
  'hawaii',
  'oklahoma',
  'utah',
  'kansas',
  'louisiana',
  'missouri',
  'vermont',
  'alaska',
  'arkansas',
  'delaware',
  'idaho',
  'maine',
  'michigan',
  'mississippi',
  'montana',
  'new-mexico',
  'north-dakota',
  'south-dakota',
  'west-virginia',
  'wyoming',
  'alabama',
  // 'district-of-columbia',
  // 'diamond-princess',
  // 'grand-princess',
  // 'puerto-rico',
  // 'guam',
  // 'virgin-islands',
]