export const BREAKPOINTS = [970, 1580]
export const START_DATE = '1/22/20'
export const STATE_MAP = {
  'WA': 'washington',
  'NY': 'new-york',
  'CA': 'california',
  'MA': 'massachusetts',
  'GA': 'georgia',
  'CO': 'colorado',
  'FL': 'florida',
  'NJ': 'new-jersey',
  'OR': 'oregon',
  'TX': 'texas',
  'IL': 'illinois',
  'PA': 'pennsylvania',
  'IA': 'iowa',
  'MD': 'maryland',
  'NC': 'north-carolina',
  'SC': 'south-carolina',
  'TN': 'tennessee',
  'VA': 'virginia',
  'AZ': 'arizona',
  'IN': 'indiana',
  'KY': 'kentucky',
  'NV': 'nevada',
  'NH': 'new-hampshire',
  'MN': 'minnesota',
  'NE': 'nebraska',
  'OH': 'ohio',
  'RI': 'rhode-island',
  'WI': 'wisconsin',
  'CT': 'connecticut',
  'HI': 'hawaii',
  'OK': 'oklahoma',
  'UT': 'utah',
  'KS': 'kansas',
  'LA': 'louisiana',
  'MO': 'missouri',
  'VT': 'vermont',
  'AK': 'alaska',
  'AR': 'arkansas',
  'DE': 'delaware',
  'ID': 'idaho',
  'ME': 'maine',
  'MI': 'michigan',
  'MS': 'mississippi',
  'MT': 'montana',
  'NM': 'new-mexico',
  'ND': 'north-dakota',
  'SD': 'south-dakota',
  'WV': 'west-virginia',
  'WY': 'wyoming',
  'AL': 'alabama',
  // 'district-of-columbia',
  // 'diamond-princess',
  // 'grand-princess',
  // 'puerto-rico',
  // 'guam',
  // 'virgin-islands',  
}
export const STATES = [
  'washington',
  'new-york',
  'california',
  'massachusetts',
  'georgia',
  'colorado',
  'florida',
  'new-jersey',
  'oregon',
  'texas',
  'illinois',
  'pennsylvania',
  'iowa',
  'maryland',
  'north-carolina',
  'south-carolina',
  'tennessee',
  'virginia',
  'arizona',
  'indiana',
  'kentucky',
  'nevada',
  'new-hampshire',
  'minnesota',
  'nebraska',
  'ohio',
  'rhode-island',
  'wisconsin',
  'connecticut',
  'hawaii',
  'oklahoma',
  'utah',
  'kansas',
  'louisiana',
  'missouri',
  'vermont',
  'alaska',
  'arkansas',
  'delaware',
  'idaho',
  'maine',
  'michigan',
  'mississippi',
  'montana',
  'new-mexico',
  'north-dakota',
  'south-dakota',
  'west-virginia',
  'wyoming',
  'alabama',
  // 'district-of-columbia',
  // 'diamond-princess',
  // 'grand-princess',
  // 'puerto-rico',
  // 'guam',
  // 'virgin-islands',
]
export const DEFAULT_SEO = {
  title: 'COVID-19',
  description: 'Global Covid-19 statistics.',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://covidstats.app/',
    site_name: 'COVID-19 Stats',
    images: [
      {
        url: 'https://covidstats.app/images/og-image.png',
        alt: 'COVID-19',
      },
    ],
  },
  twitter: {
    handle: '@trillcyborg',
    site: '@trillcyborg',
    cardType: 'summary_large_image',
  }
}